[package]
name = "rust_mcp_sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = {version="1.46.0",features = ["full"]}
thiserror = "2.0.12"
anyhow = "1.0"
futures = "0.3.31"

[[bin]]
name = "initialization_server"
path = "examples/initialization_server.rs"

[[bin]]
name = "tools_server"
path = "examples/tools_server.rs"


# Define your integration test suite
[[test]]
name = "nitialization_tests" # Name of your test suite
path = "tests/initialization_test.rs" # Path to your test file

# Define your integration test suite
[[test]]
name = "tools_tests" # Name of your test suite
path = "tests/tools_test.rs" # Path to your test file