[package]
name = "mcp_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.5.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
serde_json = "1.0.141"
syn = {version = "2.0.104", features = ["full"]}